# Generated by Django 5.2 on 2025-05-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_cartitem_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_size',
            field=models.CharField(default='Medium', max_length=20),
        ),
    ]
