# Generated by Django 5.2 on 2025-05-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_cartitem_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='product_size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
