# Generated by Django 5.2 on 2025-06-16 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_cartitem_product_size'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='cart_code',
            field=models.CharField(default='cartcode-temp', max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
    ]
